### ISSUE TITLE
Control LEDs over UART

### ISSUE THREAD

**Issue by kejace** [standardsemiconductor/VELDT-getting-started#1]
As suggestions were encouraged, I would like to see how to control the LED color and speed of the blinker. It would nicely tie together section 2 and 3.

**Comment by dopamane** [comment]
Thanks, that's a great idea! I will add it ASAP.

**Comment by dopamane** [comment]
Added [Section 4: Happylife](https://github.com/standardsemiconductor/VELDT-getting-started#section-4-happylife), includes [demo](https://github.com/standardsemiconductor/VELDT-getting-started/tree/master/demo/uart-led) of controlling LED color and blink speed via UART
